### ISSUE TITLE
Move localization infrastucture to po files

### ISSUE THREAD

**Issue by kelemeng** [WollMux/WollMux#398]
Currently the UI localization happens in a conf file:
https://github.com/WollMux/wollmux-config/blob/master/.wollmux/config/conf/localization.conf

In the long term it would be better to use po files for storing those, so those could be managed conveniently by upstream tooling like Weblate and of course more translators.

**Comment by smehrbrodt** [comment]
Agree, the UI localization from localization.conf should be moved out of the config project into this WollMux project.
However, we can't drop the existing localization format, since it is also used to translate strings from the configuration which also appear in the UI (and those strings can be modified by wollmux users).
